### PR TITLE
Claiming locations

### PR DESCRIPTION
**Pull request by ugotsoul**
From #657 

image

image

- [x] add a "claimed" field to the location so users can add themselves as responsible for a location
- [x] and a claimed time/date stamp field as well
- [x] add a filter to the locations table page for Claimed w/ options All / Claimed by you / Claimed by anyone / unclaimed
- [x] show "Is pending review" and "Claimed by" as columns in the locations table page between "request a call" and "full address"
- [x] Add bulk action options "Claim locations" and "Unclaim locations you have claimed"
- [x]  Add Location tags and Location Report Notes 
- [x]  When bulk approving locations, add a note and a tag that says "Approved"
- [x]  Make it so its easier to review claimed locations (review them consecutively)

Additional stuff I did:
- Fix: use logic to display an "s" if the claimed or unclaimed count is greater than 1 in the display message.
- Consolidate logic used by both reporters and locations actions into generic methods

---

How to test this:
- Navigate to the locations list page
- Edit some locations and set `is_pending_review`  flags to true, and on others claim the locations
- Select bulk action options in dropdown on locations list
- Go to the location review note page. 
- Check if a note was created after bulk approving for the location you selected.
- Claim some locations, then go on the locations list page and select the action to mass unclaimed locations. 
- Check `is_pending_review` on several locations, then navigate to a location show page, uncheck `is_pending_review` scroll to the bottom, and select "save and review next pending location". Then verify it worked (correct number of pending review locations, and previous location is not under review.

### CODE REVIEW

**Comment by simonw** [comment]
Looking at this now!

**Comment by simonw** [comment]
This looks spot-on. Let's deploy it to staging and try it out there a bit!

**Comment by simonw** [comment]
I'm going to rebase-and-merge rather than squash-and-merge because it looks like the commit history here is worth keeping as-is.

**Comment by simonw** [comment]
Claiming_locations_by_ugotsoul_·_Pull_Request__671_·_CAVaccineInventory_vial

I'm going to squash-and-merge instead.

**Comment by ugotsoul** [comment]
Oops, I forgot to add the fields for reviewing locations notes in the admin view, like this for reports:

image

Will open another PR for this

**Pull request merged**
